# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
            #memory: ~
        our_users:
            entity: {class: AppBundle\Entity\User, property: email}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            # Custom security authenticator
            guard:
                authenticators:
                    - app.security.login_form_authenticator

            logout:
                path: /logout

            switch_user: ~

    access_control:
        #- {path: ^/admin, roles: ROLE_ADMIN}

    # role_hierarchy allow us to categorize role permission
    # ROLE_ALLOWED_TO_SWITCH let us switch the logged in user to another user
    # To use it just add "?_switch_user=new_user+3@gmail.com" in the url we would like to access
    # Be careful with the "+ sign" which represent a space in URLS.
    # To use a "+ sign" in an URL we have to replace it with the url-encoded plus "%2B"
    # To exit just use "?_switch_user=_exit" to any URL.
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGE_GENUS, ROLE_ALLOWED_TO_SWITCH]
